<a href="https://colab.research.google.com/github/andrew3690/F-A_root_project/blob/Brazil/Data_Formating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install pyarrow
! pip install fastparquet

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyarrow in /home/andrel/.local/lib/python3.10/site-packages (12.0.1)
Requirement already satisfied: numpy>=1.16.6 in /home/andrel/.local/lib/python3.10/site-packages (from pyarrow) (1.25.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: fastparquet in /home/andrel/.local/lib/python3.10/site-packages (2023.4.0)
Requirement already satisfied: packaging in /home/andrel/.local/lib/python3.10/site-packages (from fastparquet) (23.1)
Requirement already satisfied: cramjam>=2.3 in /home/andrel/.local/lib/python3.10/site-packages (from fastparquet) (2.6.2)
Requirement already satisfied: pandas>=1.5.0 in /home/andrel/.local/lib/python3.10/site-packages (from fastparquet) (2.0.2)
Requirement already satisfied: numpy>=1.20.3 in /home/andrel/.local/lib/python3.10/site-packages (from fastparquet) (1.25.0)
Requirement already satisfied: fsspec in /home/andrel/.local/lib/python3.10/site-packages (from fastparquet) (2023.6.0)
Requirement already satisfied: tzdata>=2022.1 in /home/andrel/.local/lib/python3.10/site-packages (from pandas>=1.5.0->fastparquet) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/andrel/.local/lib/python3.10/site-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=1.5.0->fastparquet) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)

In [2]:
import pandas as pd
import os

Gooogle Colab Version

In [3]:
""" 
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
 """

" \nfrom google.colab import drive\ndrive.mount('/content/gdrive', force_remount=True)\n "

Local Machine Version

In [4]:
data  = pd.read_parquet(r"../RAW_DATA/Parquet/Valuation.parquet")

In [6]:
for column in data.columns:
    print(column)

asOfDate
periodType
EnterpriseValue
EnterprisesValueEBITDARatio
EnterprisesValueRevenueRatio
ForwardPeRatio
MarketCap
PbRatio
PeRatio
PsRatio
Symbol
PegRatio

In [7]:
data

,asOfDate,periodType,EnterpriseValue,EnterprisesValueEBITDARatio,EnterprisesValueRevenueRatio,ForwardPeRatio,MarketCap,PbRatio,PeRatio,PsRatio,Symbol,PegRatio
0,2022-06-30,3M,1.298112e+09,-24.218047,16.640536,NaN,4.456286e+08,NaN,NaN,2.318868,AVLL3.SA,NaN
1,2022-09-30,3M,1.181684e+09,-20.298270,15.321873,NaN,3.187531e+08,NaN,NaN,1.602146,AVLL3.SA,NaN
2,2022-12-31,3M,1.041477e+09,-24.571240,12.589928,NaN,1.561286e+08,NaN,NaN,0.642829,AVLL3.SA,NaN
3,2023-03-07,TTM,1.016381e+09,NaN,NaN,NaN,1.310325e+08,NaN,NaN,0.539501,AVLL3.SA,NaN
4,2023-03-08,TTM,NaN,-4.615736,4.146089,NaN,NaN,NaN,NaN,NaN,AVLL3.SA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2445,2022-09-30,3M,2.399668e+10,30.146957,20.119827,NaN,1.708714e+10,0.970073,5.350596,2.539061,TRPL4.SA,NaN
2446,2022-12-31,3M,2.345525e+10,38.624024,19.041629,11.1732,1.668905e+10,0.942804,5.868245,2.679464,TRPL4.SA,NaN
2447,2023-03-31,3M,2.261832e+10,19.855294,14.399042,10.6952,1.582047e+10,0.882587,6.311436,2.619721,TRPL4.SA,NaN
2448,2023-07-21,TTM,2.574379e+10,NaN,NaN,14.4300,1.875772e+10,0.970798,6.655543,2.901636,TRPL4.SA,NaN
2449,2023-07-24,TTM,NaN,7.085391,4.547305,NaN,NaN,NaN,NaN,NaN,TRPL4.SA,NaN

In [8]:
cols = ["PegRatio"]

data.drop(columns=cols,inplace=True)

In [9]:
data = data.dropna()

In [10]:
data['Symbol'] = data['Symbol'].str.replace('.SA', '')

/tmp/ipykernel_10892/2059340453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Symbol'] = data['Symbol'].str.replace('.SA', '')

In [11]:
data

,asOfDate,periodType,EnterpriseValue,EnterprisesValueEBITDARatio,EnterprisesValueRevenueRatio,ForwardPeRatio,MarketCap,PbRatio,PeRatio,PsRatio,Symbol
33,2023-03-31,3M,3.614854e+09,27.364323,6.075835,7.7882,3.719215e+09,4.947495,11.351973,1.658959,CURY3
44,2022-06-30,3M,8.969559e+09,20.137261,1.724256,8.5106,7.467590e+09,1.131469,19.882353,0.945369,GMAT3
45,2022-09-30,3M,1.604025e+10,30.873939,2.708069,11.0375,1.458168e+10,2.125277,34.736842,1.166018,GMAT3
46,2022-12-31,3M,1.644982e+10,40.953987,2.712444,10.9170,1.396307e+10,1.953334,31.600000,1.499898,GMAT3
47,2023-03-31,3M,1.403530e+10,33.313627,2.391886,9.8425,1.263746e+10,1.695028,26.000000,1.256262,GMAT3
...,...,...,...,...,...,...,...,...,...,...,...
2431,2023-03-31,3M,1.909848e+10,29.864797,27.562512,3.2584,1.202546e+10,1.835621,8.322398,4.609529,TAEE4
2438,2022-12-31,3M,2.345525e+10,38.624024,19.041629,14.5138,1.668905e+10,1.186703,7.386335,3.372630,TRPL3
2439,2023-03-31,3M,2.261832e+10,19.855294,14.399042,13.6426,1.582047e+10,1.126143,8.053124,3.342653,TRPL3
2446,2022-12-31,3M,2.345525e+10,38.624024,19.041629,11.1732,1.668905e+10,0.942804,5.868245,2.679464,TRPL4
2447,2023-03-31,3M,2.261832e+10,19.855294,14.399042,10.6952,1.582047e+10,0.882587,6.311436,2.619721,TRPL4

In [12]:
output_directory = "../Final/Parquet/"

# Create the output directory if it doesn't exist
os.makedirs(output_directory, exist_ok=True)

output_directory = output_directory + "" + "/Valuation.parquet"

data.to_parquet(output_directory)